name: Bug Report
description: Help us improve tgx-core.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve tgx-core. If you have questiongs instead, please visit the provided support platforms.

        [Telegram](https://web.telegram.org/a/#-1002384223877_2)

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: "Code Example"
      description: |
        Please provide a clear and understandable code example in reproducing this bug.
      render: typescript
    validations:
      required: true

  - type: textarea
    id: runtime-description
    attributes:
      label: "Runtime Description"
      description: |
        Provide a list of the versions you're using, but not limited to:
      placeholder: |
        - tgx-core 0.0.0 "npm ls"
        - Node.js 0.0.0 "node -v"
        - TypeScript|JavaScript 0.0.0 "typescript -v"
        - Windows
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority Level"
      description: "In your descretion, select the priority level of this bug."
      options:
        - Low
        - Medium
        - High
    validations:
      required: true